# Generated by Django 5.1.3 on 2024-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=400)),
                ('product_type', models.CharField(max_length=100)),
                ('product_url', models.CharField(max_length=200)),
                ('product_img_link', models.CharField(max_length=200)),
            ],
        ),
    ]
